/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package holoeditor.view;

import holoeditor.service.*;
import javax.swing.JFrame;

/**
 *
 * @author nehardt
 */
public class EditorJFrame extends JFrame
{
    EditorService editorService;
    SerialService serialService;
    FileService fileService;

    EditorMenuBar menuBar;
    CircleEditPanel circlePanel;
    RectEditPanel rectPanel;
    
    public EditorJFrame(
            EditorService editorService,
            SerialService serialService,
            FileService fileService) {
        super("HoloEditor"); // set frame title
        
        this.editorService = editorService;
        this.serialService = serialService;
        this.fileService = fileService;
        
        initComponents();
        initMoreComponents();
        
        setSize(700, 400);
    }
    
    private void initMoreComponents() {
        menuBar = new EditorMenuBar(editorService, fileService);
        setJMenuBar(menuBar);
        
        circlePanel = new CircleEditPanel(editorService);
        centerPanel.add(circlePanel);
        rectPanel = new RectEditPanel(editorService);
        centerPanel.add(rectPanel);
        
        statusLabel.setText("Starting...");
        serialService.addListener(new SerialService.Adapter () {
            @Override
            public void scanningPort(String portName) {
                statusLabel.setText("Scanning port "+portName+"...");
            }
            @Override
            public void connectedToPort(String portName) {
                statusLabel.setText("Connected to port "+portName+".");
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        centerPanel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        statusLabel = new javax.swing.JLabel();
        reconnectButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        centerPanel.setLayout(new java.awt.GridLayout(1, 2));
        getContentPane().add(centerPanel, java.awt.BorderLayout.CENTER);

        jPanel1.setLayout(new java.awt.BorderLayout());

        statusLabel.setText("status label");
        jPanel1.add(statusLabel, java.awt.BorderLayout.CENTER);

        reconnectButton.setText("Reconnect");
        reconnectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reconnectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(reconnectButton, java.awt.BorderLayout.LINE_END);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void reconnectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reconnectButtonActionPerformed
        serialService.tryNextPort();
    }//GEN-LAST:event_reconnectButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel centerPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton reconnectButton;
    private javax.swing.JLabel statusLabel;
    // End of variables declaration//GEN-END:variables
}
